project:
  type: website

website:
  title: "Jiecheng Zhu"
  navbar:
    pinned: true
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About You
      - href: projects.qmd
        text: Projects
      - href: cv.qmd
        text: CV
      - href: contact.qmd
        text: Contact

  page-footer:
    center: "© 2026 Jiecheng Zhu. Built with Quarto."

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false
    smooth-scroll: true
    link-external-newwindow: true

execute:
  echo: false
  warning: false
